apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
              - sh
              - /check.sh
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
  - name: pma
    protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer  