apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
              - sh
              - /check.sh
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
            - containerPort: 21
            - containerPort: 21100
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
  - name: passive
    port: 21100
    targetPort: 21100
  type: LoadBalancer  